-- 1. 온라인 판매 데이터 조회
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'

UNION ALL

-- 2. 오프라인 판매 데이터 조회 (USER_ID는 NULL로 채움)
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'

-- 3. 전체 합쳐진 결과 정렬
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;