# 온라인 판매 정보 테이블, 오프라인 판매 정보 테이블. JOIN안됨
# 2022 3월 오프/온라 합쳐서 표시. 단 오프라인 user_id는 null로!
# 판매일 기준으로 오름차순, 상품 ID 오름차순
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

UNION ALL

SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'

ORDER BY SALES_DATE, PRODUCT_ID, IFNULL(USER_ID, 0)