# 가입, 판매 테이블
# 2021년 가입하고 구매한 수 / 2021년 가입자 수 ROUND(, 1)
# 년 오름차순 ,월 오름차순
SELECT 
    YEAR(S.SALES_DATE) AS YEAR, 
    MONTH(S.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / 
          (SELECT COUNT(USER_ID)
           FROM USER_INFO
           WHERE YEAR(JOINED) = 2021)
          , 1) AS PUCHASED_RATIO
FROM USER_INFO AS U
JOIN ONLINE_SALE AS S ON U.USER_ID = S.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;