SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS P -- 1. 부모 아이템 정보
JOIN ITEM_TREE AS T ON P.ITEM_ID = T.PARENT_ITEM_ID -- 2. 부모의 ID를 부모_ID 컬럼과 연결
JOIN ITEM_INFO AS I ON T.ITEM_ID = I.ITEM_ID -- 3. 연결된 자식 ID로 자식 아이템 정보 조회
WHERE P.RARITY = 'RARE'
ORDER BY I.ITEM_ID DESC;