SELECT 
    MONTH(START_DATE) AS MONTH, 
    CAR_ID, 
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- 2단계: 선발된 '우수 자동차' 명단에 있는 데이터만 가져옵니다.
WHERE CAR_ID IN (
    -- 1단계: 8~10월 총 대여 횟수가 5회 이상인 자동차 ID만 추출
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
-- 2단계 추가 조건: 메인 리스트도 8~10월 데이터로 한정합니다.
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;