SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') # 참일 때
   OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') # 참일 때
ORDER BY ID ASC;