# 카테고리 별 도서 판매량 합산, 
# 카테고리명 기준 오름차순
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1 
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY